# Generated by Django 5.2.15 on 2026-06-27 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RentalContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("monthly_rent", models.DecimalField(decimal_places=2, max_digits=10)),
                ("due_day", models.PositiveIntegerField(default=5)),
                (
                    "security_deposit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Expired", "Expired"),
                            ("Terminated", "Terminated"),
                            ("Pending", "Pending"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="StallType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("municipality_name", models.CharField(max_length=200)),
                ("market_name", models.CharField(max_length=200)),
                ("office_name", models.CharField(max_length=200)),
                ("receipt_prefix", models.CharField(max_length=20)),
                ("default_due_day", models.PositiveIntegerField(default=5)),
                (
                    "penalty_type",
                    models.CharField(
                        choices=[("fixed", "Fixed"), ("percentage", "Percentage")],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                (
                    "penalty_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("grace_period", models.PositiveIntegerField(default=5)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                ("theme_color", models.CharField(default="#003366", max_length=7)),
            ],
            options={
                "verbose_name": "System Setting",
                "verbose_name_plural": "System Settings",
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("module", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PenaltySetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "penalty_type",
                    models.CharField(
                        choices=[("fixed", "Fixed"), ("percentage", "Percentage")],
                        default="percentage",
                        max_length=20,
                    ),
                ),
                ("penalty_value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("grace_period", models.PositiveIntegerField(default=5)),
                ("due_day", models.PositiveIntegerField(default=5)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="penalty_settings",
                        to="core.rentalcontract",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_active"],
            },
        ),
        migrations.CreateModel(
            name="Stall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stall_number", models.CharField(max_length=20, unique=True)),
                (
                    "size",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("monthly_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Vacant", "Vacant"),
                            ("Occupied", "Occupied"),
                            ("Reserved", "Reserved"),
                            ("Maintenance", "Maintenance"),
                        ],
                        default="Vacant",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stalls",
                        to="core.marketsection",
                    ),
                ),
                (
                    "stall_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stalls",
                        to="core.stalltype",
                    ),
                ),
            ],
            options={
                "ordering": ["stall_number"],
            },
        ),
        migrations.AddField(
            model_name="rentalcontract",
            name="stall",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="core.stall",
            ),
        ),
        migrations.CreateModel(
            name="Billing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("billing_month", models.PositiveIntegerField()),
                ("billing_year", models.PositiveIntegerField()),
                ("rental_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "penalty_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_due", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Unpaid", "Unpaid"),
                            ("Paid", "Paid"),
                            ("Partial", "Partial"),
                            ("Overdue", "Overdue"),
                        ],
                        default="Unpaid",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billings",
                        to="core.rentalcontract",
                    ),
                ),
                (
                    "stall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billings",
                        to="core.stall",
                    ),
                ),
            ],
            options={
                "ordering": ["-billing_year", "-billing_month"],
            },
        ),
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_id", models.CharField(max_length=20, unique=True)),
                ("full_name", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("contact_number", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("valid_id_type", models.CharField(blank=True, max_length=100)),
                ("valid_id_number", models.CharField(blank=True, max_length=100)),
                ("business_name", models.CharField(blank=True, max_length=200)),
                ("business_type", models.CharField(blank=True, max_length=100)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "emergency_contact_number",
                    models.CharField(blank=True, max_length=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Active", "Active"),
                            ("Inactive", "Inactive"),
                            ("Suspended", "Suspended"),
                            ("Terminated", "Terminated"),
                        ],
                        default="Active",
                        max_length=20,
                    ),
                ),
                ("date_registered", models.DateField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tenant",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["full_name"],
            },
        ),
        migrations.AddField(
            model_name="rentalcontract",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="core.tenant",
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receipt_number", models.CharField(max_length=50, unique=True)),
                ("billing_month", models.PositiveIntegerField()),
                ("billing_year", models.PositiveIntegerField()),
                ("rental_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "penalty_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_amount_due",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("amount_paid", models.DecimalField(decimal_places=2, max_digits=10)),
                ("payment_date", models.DateField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("Cash", "Cash"),
                            ("GCash", "GCash"),
                            ("Bank Transfer", "Bank Transfer"),
                            ("Check", "Check"),
                        ],
                        default="Cash",
                        max_length=20,
                    ),
                ),
                ("official_receipt_no", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Paid", "Paid"),
                            ("Partial", "Partial"),
                            ("Void", "Void"),
                            ("Cancelled", "Cancelled"),
                        ],
                        default="Paid",
                        max_length=20,
                    ),
                ),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "billing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="core.billing",
                    ),
                ),
                (
                    "collected_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collected_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stall",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="core.stall",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="Notice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notice_type",
                    models.CharField(
                        choices=[
                            ("Payment Reminder", "Payment Reminder"),
                            ("Overdue Notice", "Overdue Notice"),
                            ("Final Demand", "Final Demand"),
                            ("Vacancy Notice", "Vacancy Notice"),
                        ],
                        max_length=30,
                    ),
                ),
                ("notice_number", models.CharField(max_length=50, unique=True)),
                ("date_issued", models.DateField()),
                ("is_served", models.BooleanField(default=False)),
                ("served_date", models.DateField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notices",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_issued"],
            },
        ),
        migrations.AddField(
            model_name="billing",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billings",
                to="core.tenant",
            ),
        ),
        migrations.CreateModel(
            name="TenantLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_date", models.DateField()),
                ("description", models.CharField(max_length=255)),
                (
                    "debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "billing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to="core.billing",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to="core.payment",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Tenant Ledgers",
                "ordering": ["transaction_date"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("collector", "Collector"),
                            ("supervisor", "Supervisor"),
                            ("treasurer", "Treasurer"),
                            ("tenant", "Tenant"),
                        ],
                        default="tenant",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="rentalcontract",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "Active")),
                fields=("stall", "status"),
                name="unique_active_contract_per_stall",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="billing",
            unique_together={("tenant", "stall", "billing_month", "billing_year")},
        ),
    ]
