# Generated by Django 6.0.6 on 2026-08-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('collector', 'Collector'), ('cashier', 'Cashier'), ('supervisor', 'Supervisor'), ('treasurer', 'Treasurer'), ('tenant', 'Tenant')], default='tenant', max_length=20),
        ),
    ]
